"""
Metrics tracking utilities for comparing RL training implementations.

This module provides a unified interface for tracking performance, efficiency,
and cost metrics across different training implementations.
"""

import time
from typing import Dict, Any, Optional
from dataclasses import dataclass
import json
import csv
from pathlib import Path


@dataclass
class TokenCounts:
    """Accumulated token counts across training."""

    training: int = 0  # Tokens used in forward-backward passes
    sampling: int = 0  # Tokens generated during rollouts
    prompt: int = 0  # Prompt tokens sent to model
    completion: int = 0  # Completion tokens generated

    def to_dict(self) -> Dict[str, int]:
        return {
            "training": self.training,
            "sampling": self.sampling,
            "prompt": self.prompt,
            "completion": self.completion,
        }


@dataclass
class CostModel:
    """Cost model for estimating training expenses."""

    training_rate_per_1k: float = 0.01  # $ per 1k training tokens
    sampling_rate_per_1k: float = 0.005  # $ per 1k sampling tokens

    def calculate_training_cost(self, tokens: int) -> float:
        return (tokens / 1000.0) * self.training_rate_per_1k

    def calculate_sampling_cost(self, tokens: int) -> float:
        return (tokens / 1000.0) * self.sampling_rate_per_1k

    def calculate_total_cost(self, training_tokens: int, sampling_tokens: int) -> float:
        return self.calculate_training_cost(training_tokens) + self.calculate_sampling_cost(
            sampling_tokens
        )


class MetricsTracker:
    """
    Comprehensive metrics tracker for RL training experiments.

    Tracks:
    - Performance metrics (loss, accuracy, rewards)
    - Timing metrics (step time, component breakdowns)
    - Token counts (training, sampling, prompts, completions)
    - Cost estimates
    - Operational metrics (failures, retries)
    """

    def __init__(
        self,
        implementation_name: str,
        cost_model: Optional[CostModel] = None,
        output_dir: Optional[str] = None,
    ):
        self.implementation = implementation_name
        self.cost_model = cost_model or CostModel()
        self.output_dir = Path(output_dir) if output_dir else Path("metrics_output")
        self.output_dir.mkdir(exist_ok=True)

        # Tracking state
        self.step_metrics: Dict[str, Any] = {}
        self.component_times: Dict[str, float] = {}
        self.token_counts = TokenCounts()
        self.failure_count = 0
        self.current_step = 0

        # History for analysis
        self.metrics_history = []

        # CSV logging
        self.csv_file = self.output_dir / f"{implementation_name}_metrics.csv"
        self.csv_headers = None
        self.csv_writer = None

    def start_step(self, step: int) -> None:
        """Begin tracking a new training step."""
        self.current_step = step
        self.step_metrics = {
            "step": step,
            "implementation": self.implementation,
            "step_start_time": time.time(),
        }
        self.component_times = {}

    def start_component(self, component_name: str) -> None:
        """Start timing a component (e.g., 'data_fetch', 'forward_backward')."""
        self.component_times[component_name] = time.time()

    def end_component(self, component_name: str) -> float:
        """
        End timing a component and record elapsed time.

        Returns:
            float: Elapsed time in seconds
        """
        if component_name not in self.component_times:
            print(f"Warning: Component '{component_name}' was never started")
            return 0.0

        elapsed = time.time() - self.component_times[component_name]
        self.step_metrics[f"time/{component_name}"] = elapsed
        return elapsed

    def add_token_counts(
        self,
        training_tokens: int = 0,
        sampling_tokens: int = 0,
        prompt_tokens: int = 0,
        completion_tokens: int = 0,
    ) -> None:
        """
        Add token counts for the current step.

        Args:
            training_tokens: Tokens used in forward-backward pass
            sampling_tokens: Tokens generated during rollout sampling
            prompt_tokens: Prompt tokens sent to model
            completion_tokens: Completion tokens generated by model
        """
        # Update cumulative counts
        self.token_counts.training += training_tokens
        self.token_counts.sampling += sampling_tokens
        self.token_counts.prompt += prompt_tokens
        self.token_counts.completion += completion_tokens

        # Record step-level and cumulative metrics
        self.step_metrics.update(
            {
                "tokens/training_step": training_tokens,
                "tokens/sampling_step": sampling_tokens,
                "tokens/prompt_step": prompt_tokens,
                "tokens/completion_step": completion_tokens,
                "tokens/training_total": self.token_counts.training,
                "tokens/sampling_total": self.token_counts.sampling,
                "tokens/prompt_total": self.token_counts.prompt,
                "tokens/completion_total": self.token_counts.completion,
            }
        )

    def calculate_costs(self) -> Dict[str, float]:
        """
        Calculate cost metrics based on current token counts.

        Returns:
            Dict with cost/training, cost/sampling, cost/total, cost/per_step
        """
        train_cost = self.cost_model.calculate_training_cost(self.token_counts.training)
        sample_cost = self.cost_model.calculate_sampling_cost(self.token_counts.sampling)
        total_cost = train_cost + sample_cost
        per_step_cost = total_cost / (self.current_step + 1) if self.current_step >= 0 else 0.0

        costs = {
            "cost/training": train_cost,
            "cost/sampling": sample_cost,
            "cost/total": total_cost,
            "cost/per_step": per_step_cost,
        }

        self.step_metrics.update(costs)
        return costs

    def record_failure(self, error_msg: str = "") -> None:
        """Record a failure or retry event."""
        self.failure_count += 1
        self.step_metrics["failures/count"] = self.failure_count
        if error_msg:
            self.step_metrics["failures/last_error"] = error_msg

    def end_step(
        self,
        loss: float,
        reward_mean: float,
        additional_metrics: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Complete the current step and finalize metrics.

        Args:
            loss: Training loss for this step
            reward_mean: Mean reward across batch
            additional_metrics: Any extra metrics to include

        Returns:
            Dict of all metrics for this step
        """
        # Calculate total step time
        total_time = time.time() - self.step_metrics["step_start_time"]
        self.step_metrics["step_time_total"] = total_time

        # Add core metrics
        self.step_metrics["train/loss"] = loss
        self.step_metrics["reward/mean"] = reward_mean

        # Add any additional metrics
        if additional_metrics:
            self.step_metrics.update(additional_metrics)

        # Calculate costs
        self.calculate_costs()

        # Remove the start time from final metrics (internal tracking only)
        metrics_to_log = {k: v for k, v in self.step_metrics.items() if k != "step_start_time"}

        # Save to history
        self.metrics_history.append(metrics_to_log.copy())

        # Log to CSV
        self._write_csv_row(metrics_to_log)

        return metrics_to_log

    def _write_csv_row(self, metrics: Dict[str, Any]) -> None:
        """Write a row to the CSV file."""
        try:
            # Initialize CSV writer if needed
            if self.csv_writer is None:
                file_exists = self.csv_file.exists()
                self.csv_file_handle = open(self.csv_file, "a", newline="")

                if not file_exists:
                    # First time: write headers
                    self.csv_headers = sorted(metrics.keys())
                    self.csv_writer = csv.DictWriter(
                        self.csv_file_handle,
                        fieldnames=self.csv_headers,
                    )
                    self.csv_writer.writeheader()
                else:
                    # File exists: read headers from file
                    with open(self.csv_file, "r") as f:
                        reader = csv.reader(f)
                        self.csv_headers = next(reader)
                    self.csv_writer = csv.DictWriter(
                        self.csv_file_handle,
                        fieldnames=self.csv_headers,
                    )

            # Write row (only include fields that match headers)
            row = {k: metrics.get(k, "") for k in self.csv_headers}
            self.csv_writer.writerow(row)
            self.csv_file_handle.flush()

        except Exception as e:
            print(f"Warning: Failed to write CSV row: {e}")

    def save_checkpoint(self, step: int) -> None:
        """Save a JSON checkpoint with complete state."""
        checkpoint = {
            "implementation": self.implementation,
            "step": step,
            "token_counts": self.token_counts.to_dict(),
            "failure_count": self.failure_count,
            "metrics_history": self.metrics_history,
        }

        checkpoint_file = self.output_dir / f"{self.implementation}_checkpoint_step_{step}.json"
        with open(checkpoint_file, "w") as f:
            json.dump(checkpoint, f, indent=2)

        print(f"Saved checkpoint to {checkpoint_file}")

    def get_summary_stats(self) -> Dict[str, Any]:
        """
        Get summary statistics across all steps.

        Returns:
            Dict with mean, std, min, max for key metrics
        """
        if not self.metrics_history:
            return {}

        import numpy as np

        summary = {
            "total_steps": len(self.metrics_history),
            "total_failures": self.failure_count,
            "token_counts": self.token_counts.to_dict(),
        }

        # Calculate stats for numeric metrics
        for key in ["step_time_total", "train/loss", "reward/mean"]:
            values = [m.get(key) for m in self.metrics_history if key in m]
            if values:
                summary[f"{key}/mean"] = float(np.mean(values))
                summary[f"{key}/std"] = float(np.std(values))
                summary[f"{key}/min"] = float(np.min(values))
                summary[f"{key}/max"] = float(np.max(values))

        # Final costs
        if self.metrics_history:
            last_metrics = self.metrics_history[-1]
            summary["final_cost_total"] = last_metrics.get("cost/total", 0.0)
            summary["final_cost_per_step"] = last_metrics.get("cost/per_step", 0.0)

        return summary

    def close(self) -> None:
        """Clean up resources."""
        if hasattr(self, "csv_file_handle"):
            self.csv_file_handle.close()

        # Save final summary
        summary = self.get_summary_stats()
        summary_file = self.output_dir / f"{self.implementation}_summary.json"
        with open(summary_file, "w") as f:
            json.dump(summary, f, indent=2)

        print(f"\n{'='*60}")
        print(f"Metrics Summary for {self.implementation}")
        print(f"{'='*60}")
        print(f"Total steps: {summary.get('total_steps', 0)}")
        print(f"Total failures: {summary.get('total_failures', 0)}")
        print(f"Mean step time: {summary.get('step_time_total/mean', 0):.2f}s")
        print(f"Final cost: ${summary.get('final_cost_total', 0):.4f}")
        print(f"Cost per step: ${summary.get('final_cost_per_step', 0):.4f}")
        print(f"Total training tokens: {self.token_counts.training:,}")
        print(f"Total sampling tokens: {self.token_counts.sampling:,}")
        print(f"{'='*60}\n")


def count_tokens_from_tinker_data(data) -> Dict[str, int]:
    """
    Count tokens from Tinker Datum objects.

    Args:
        data: List of tinker.Datum objects

    Returns:
        Dict with training_tokens and prompt_tokens
    """
    training_tokens = 0
    prompt_tokens = 0

    for datum in data:
        # Count total tokens in forward pass
        tokens = datum.model_input.tokens
        training_tokens += len(tokens)

        # Count prompt tokens (those with advantage = 0.0)
        if "advantages" in datum.loss_fn_inputs:
            advantages = datum.loss_fn_inputs["advantages"].to_torch()
            prompt_tokens += (advantages == 0.0).sum().item()

    return {
        "training_tokens": training_tokens,
        "prompt_tokens": prompt_tokens,
    }


def count_tokens_from_atropos_batch(batch: Dict[str, Any]) -> Dict[str, int]:
    """
    Count tokens from Atropos batch format.

    Args:
        batch: Atropos batch dictionary

    Returns:
        Dict with sampling_tokens, prompt_tokens, completion_tokens
    """
    sampling_tokens = 0
    prompt_tokens = 0
    completion_tokens = 0

    if "batch" in batch and batch["batch"] is not None:
        for group in batch["batch"]:
            for item in group:
                # Count all generated tokens
                if "tokens" in item:
                    for token_seq in item["tokens"]:
                        sampling_tokens += len(token_seq)

                # Split into prompt vs completion
                if "prompt_length" in item:
                    for token_seq in item["tokens"]:
                        plen = item["prompt_length"]
                        prompt_tokens += plen
                        completion_tokens += max(0, len(token_seq) - plen)

    return {
        "sampling_tokens": sampling_tokens,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
    }
